server:
  port: 8888
mybatis-plus:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  configuration:
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # \u5173\u95ED mybatis-plus\u7684 banner
    banner: false

spring:
  datasource:
    username: date_platform
    password: gxzd_date
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rdseymkium0m90g55fd7.mysql.cloud.echargenet.com:3306/analyze_platform?useUnicode=true&amp;characterEncoding=utf8&useSSL=false&amp;autoReconnect=true
    # 初始化时建立物理连接个数
    initialSize: 5
    # 最小连接池数量
    minIdle: 5
    # 最大连接池数量
    maxActive: 50
    # 获取连接最大等待时间
    maxWait: 60000
    # 监控页登录信息
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  mvc:
    #view:
      #prefix: /
      #suffix: .html

    throw-exception-if-no-handler-found: true
    static-path-pattern: /statics/**
  devtools:
    restart:
      enabled: true #\u8BBE\u7F6E\u5F00\u542F\u70ED\u90E8\u7F72
      additional-paths: src/main/java #\u91CD\u542F\u76EE\u5F55
      exclude: WEB-INF/**
  freemarker:
    cache: false #\u9875\u9762\u4E0D\u52A0\u8F7D\u7F13\u5B58\uFF0C\u4FEE\u6539\u5373\u65F6\u751F\u6548

